apiVersion: apps/v1
kind: Deployment
metadata:
  name: decentered-events
  labels:
    app: decentered-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: decentered-backend
  template:
    metadata:
      labels:
        app: decentered-backend
    spec:
      containers:
      - name: python-backend
        image: noamsml/decentered-events:latest
        volumeMounts:
          - name: config
            mountPath: "/app/config/injected"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: backend-config.events
            items:
            - key: "containerized.json"
              path: "containerized.json"