apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config.events
data:
 containerized.json: |
  {
    "database": {
        "username": {"env": "DATABASE_USERNAME"},
        "password": {"env": "DATABASE_PASSWORD"},
        "host": "mysql"
    },
    "google_token": "config/credentials/serviceaccount.json",
    "base_row": 700
  }