name: ci

on:
  push:
    branches: 
      - main

env:
  BACKEND_LATEST_TAG: noamsml/decentered-events:latest
  FRONTEND_LATEST_TAG: noamsml/decentered-frontend:latest
  DOCKERHUB_USERNAME: noamsml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # TODO add testing stage
      # - name: Build and export to Docker
      #   uses: docker/build-push-action@v6
      #   with:
      #     load: true
      #     tags: ${{ env.TEST_TAG }}

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}          

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: kubernetes/containers/backend.dockerfile
          tags: ${{ env.BACKEND_LATEST_TAG }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: kubernetes/containers/frontend.dockerfile
          tags: ${{ env.FRONTEND_LATEST_TAG }}